### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [audreyshub/lucybobble#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by audreyshub** [comment]
Yay, I added the meta tag and app looks beautiful on mobile. Thanks Marco! :)

**Comment by MarcoMorawec** [comment]
:+1: @audreyshub 

Also, make sure you close this issue, since you fixed your code :)
